# Generated by Django 2.2.4 on 2021-02-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_connector_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='testapp.CountryCode'),
        ),
    ]
