# Generated by Django 2.2.4 on 2021-02-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_place_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='restaurant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
