# Generated by Django 2.2.4 on 2021-02-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20210211_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Restaurant'),
        ),
    ]
